USE MEMBER;
DROP TABLE TEAM_INFO,MEMBER_INFO;
CREATE TABLE IF NOT EXISTS TEAM_INFO(
	TEAM_CODE INT PRIMARY KEY AUTO_INCREMENT COMMENT "소속코드",
    TEAM_NAME VARCHAR(100) NOT NULL COMMENT "소속명",
    TEAM_DETAIL VARCHAR(500)  COMMENT "소속상세정보",
    USE_YN CHAR(2) NOT NULL CHECK (USE_YN IN ('Y','N')) DEFAULT 'Y' COMMENT "사용여부" 
) ENGINE = INNODB;



CREATE TABLE IF NOT EXISTS MEMBER_INFO(
	MEMBER_CODE INT PRIMARY KEY AUTO_INCREMENT COMMENT "회원코드",
    MEMBER_NAME VARCHAR(70) NOT NULL COMMENT "회원이름",
    BIRTH_DATE DATE COMMENT "생년월일",
    DIVISION_CODE CHAR(2) COMMENT "구분코드",
    DETAIL_INFO VARCHAR(500) COMMENT"상세정보",
    CONTACT VARCHAR(50) NOT NULL COMMENT"연락처",
    TEAM_CODE INT NOT NULL COMMENT"소속코드",
    ACTIVE_STATUS CHAR(2) NOT NULL CHECK(ACTIVE_STATUS IN ('Y','N','H'))DEFAULT 'Y'COMMENT"활동상태",
    FOREIGN KEY(TEAM_CODE) 
		REFERENCES TEAM_INFO(TEAM_CODE)
) ENGINE= INNODB;

DESCRIBE MEMBER_INFO;
DESCRIBE TEAM_INFO;
 
INSERT INTO TEAM_INFO
VALUES
(1,"음악감상부","클래식 및 재즈 음식을 감상하는 사람",'Y'),
(2,"맛집탐방부","맛집을 찾아다니는 사람들의 모임",'N'),
(3,"행복찾기부",null,'Y');

select * from team_info;

INSERT INTO MEMBER_INFO 
-- (MEMBER_CODE, MEMBER_NAME, BIRTH_DATE, DIVISION_CODE, DETAIL_INFO, CONTACT, TEAM_CODE, ACTIVE_STATUS)
VALUES
(1, "송가인", "1990-01-30", 1, "안녕하세요 송가인입니다~", "010-9494-9494", 1, "H"),
(2, "임영웅", "1992-05-03", NULL, "국민아들 임영웅입니다~", "hero@trot.com", 1, "Y"),
(3, "태진아", NULL, NULL, NULL, "(1급 기밀)", 3, "Y");


SELECT * FROM MEMBER_INFO;